version: "3"

services:
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${1299alarslan1}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <030718044>
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./wordpress:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email alarslannn@gmail.com --agree-tos --no-eff-email -d yourdomain.com
